### ISSUE TITLE
Analyzer fails watching Nintendo Switch CC traffic getting into DP Alt mode

### ISSUE THREAD

**Issue by JBohr** [eugenecyyeh/PD3.0-analyzer#1]
I am looking to further understand how the Nintendo Switch gets into its MyDP/DP Alt mode to send video over the USB-C cable. When running the PD3.0 Analyzer it runs into the following errors when trying to follow the Nintendo Switch CC traffic:

```
File "C:\Redacted\HighLevelAnalyzer.py", line 264, in decode
    output_frame = self.engine.send(frame)

File "C:\Redacted\HighLevelAnalyzer.py", line 418, in state_machine
    VDO_header_command = data_object_data['command']
```

I am not sure how I can debug extensions to figure out what the failing value is for these lines, the last Console output is the following:

`Message Header : {'command_code': 'Vendor_Defined', 'number_of_objects': 2, 'message_id': 4, 'spec_revision': '2.0', 'power_port_role': 'Sink', 'port_data_role': 'DFP', 'raw': '0x286f'}
`

Attached is the Saleae capture. I would be interested to help figure this out/discuss. I will try poking around to see if I can do anything.
[Nintendo_SW_Video_Out_Fail.zip](https://github.com/eugenecyyeh/Saleae-PD3.0-analyzer/files/11907096/Nintendo_SW_Video_Out_Fail.zip)

**Comment by eugenecyyeh** [comment]
Hi,
the extension failed to get certain parameters defined from structured VDM header because Nintendo used their own unstructured VDM header. 
I have just uploaded the latest version v0.0.6 that skips capturing those parameters if the header is unstructured.
![image](https://github.com/eugenecyyeh/Saleae-PD3.0-analyzer/assets/121099078/e0ace4af-f938-4c14-9d10-2f60e37b9d87)

**Comment by JBohr** [comment]
Awesome! Thanks for the quick response.

I was able to print my way to seeing it was an unstructured VDM and the message/value was 0x57e0000 that was causing the failure, but didn't work out yet how to get past it.

The Saleae Extension Portal still points to v0.0.3 so I manually updated the extension, is there something you have to do to update the version the Saleae extension portal points to?

**Comment by eugenecyyeh** [comment]
Hi,
I actually did not check unstructured VDM with this extension before, so thanks for noticing me about the error. 
As for updating the extension, I had received a mail informing me that the extension gets updated in Saleae marketplace.
Could you try the 'check for updates' button to see if it starts updating?
![image](https://github.com/eugenecyyeh/Saleae-PD3.0-analyzer/assets/121099078/c5b17762-ccb1-4f06-ac45-dd73137630f4)

**Comment by JBohr** [comment]
Ah I didn't know about the update. I just went back into Saleae Logic and it actually had a popup notifying me there was an update. It now correctly points to v0.0.6.
